-- DataMind — authentication, roles, account management & audit setup
-- Run AFTER setup.sql in the EXISTING Supabase project.
-- This migration is aligned with the current schema:
--   owner_users: uuid id + display_name
--   hr_manager_users/employee_users: integer id + workforce_id + display_name
--   audit_logs: operation_type / operation_target / execution_status /
--               affected_rows / metadata

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Role-specific login tables
-- ---------------------------------------------------------------------
create table if not exists owner_users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  display_name text not null,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table if not exists hr_manager_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now(),
  workforce_id int4 null references workforce(id),
  display_name text not null,
  is_active boolean not null default true
);

create table if not exists employee_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now(),
  workforce_id int4 null references workforce(id),
  display_name text not null,
  is_active boolean not null default true
);

-- Safe migration for an existing database. CREATE TABLE IF NOT EXISTS does
-- not modify an existing table, so these ALTER statements are intentional.
alter table owner_users add column if not exists display_name text;
alter table owner_users add column if not exists is_active boolean not null default true;
update owner_users set display_name = username where display_name is null;
alter table owner_users alter column display_name set not null;

alter table hr_manager_users add column if not exists workforce_id int4;
alter table hr_manager_users add column if not exists display_name text;
alter table hr_manager_users add column if not exists is_active boolean not null default true;
update hr_manager_users set display_name = username where display_name is null;
alter table hr_manager_users alter column display_name set not null;

alter table employee_users add column if not exists workforce_id int4;
alter table employee_users add column if not exists display_name text;
alter table employee_users add column if not exists is_active boolean not null default true;
update employee_users set display_name = username where display_name is null;
alter table employee_users alter column display_name set not null;

-- ---------------------------------------------------------------------
-- Audit trail. This matches the existing DataMind table rather than the
-- earlier action/target_type/details naming.
-- ---------------------------------------------------------------------
create table if not exists audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_username text not null,
  actor_role text not null check (actor_role in ('owner', 'hr_manager', 'employee')),
  operation_type text not null,
  operation_target text,
  execution_status text not null default 'success',
  affected_rows int4,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table audit_logs add column if not exists operation_type text;
alter table audit_logs add column if not exists operation_target text;
alter table audit_logs add column if not exists execution_status text default 'success';
alter table audit_logs add column if not exists affected_rows int4;
alter table audit_logs add column if not exists metadata jsonb default '{}'::jsonb;
alter table audit_logs add column if not exists created_at timestamptz default now();

update audit_logs
set operation_type = coalesce(operation_type, 'legacy_event')
where operation_type is null;
update audit_logs
set execution_status = coalesce(execution_status, 'success')
where execution_status is null;
update audit_logs
set metadata = coalesce(metadata, '{}'::jsonb)
where metadata is null;
update audit_logs
set created_at = coalesce(created_at, now())
where created_at is null;

alter table audit_logs alter column operation_type set not null;
alter table audit_logs alter column execution_status set not null;
alter table audit_logs alter column created_at set not null;

-- Keep actor_role compatible with all three application roles even if an
-- earlier migration created a narrower check constraint.
do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.audit_logs'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%actor_role%'
  loop
    execute format('alter table public.audit_logs drop constraint if exists %I', constraint_name);
  end loop;
end $$;

alter table audit_logs
  add constraint audit_logs_actor_role_check
  check (actor_role in ('owner', 'hr_manager', 'employee'));

create index if not exists audit_logs_created_at_idx on audit_logs (created_at desc);
create index if not exists audit_logs_operation_type_idx on audit_logs (operation_type);

-- ---------------------------------------------------------------------
-- Lock account/audit tables away from browser roles.
-- ---------------------------------------------------------------------
revoke all on table owner_users from public, anon, authenticated;
revoke all on table hr_manager_users from public, anon, authenticated;
revoke all on table employee_users from public, anon, authenticated;
revoke all on table audit_logs from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- Demo accounts. Existing usernames are preserved.
-- ---------------------------------------------------------------------
insert into owner_users (username, password_hash, display_name, is_active)
values ('owner', crypt('change-me-owner', gen_salt('bf')), 'Workspace Owner', true)
on conflict (username) do nothing;

insert into hr_manager_users (username, password_hash, display_name, is_active)
values ('admin', crypt('change-me-admin', gen_salt('bf')), 'HR/Manager', true)
on conflict (username) do nothing;

insert into employee_users (username, password_hash, display_name, is_active)
values ('member', crypt('change-me-member', gen_salt('bf')), 'Employee', true)
on conflict (username) do nothing;

-- ---------------------------------------------------------------------
-- Password hashing helper
-- ---------------------------------------------------------------------
create or replace function hash_datamind_password(p_password text)
returns text
language sql
security definer
set search_path = public, extensions
as $$
  select crypt(p_password, gen_salt('bf'));
$$;

revoke all on function hash_datamind_password(text) from public, anon, authenticated;
grant execute on function hash_datamind_password(text) to service_role;

-- ---------------------------------------------------------------------
-- Role-specific login verification
-- ---------------------------------------------------------------------
create or replace function verify_owner_login(p_username text, p_password text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_match boolean;
begin
  select exists (
    select 1 from owner_users
    where username = p_username
      and is_active = true
      and password_hash = crypt(p_password, password_hash)
  ) into v_match;
  return v_match;
end;
$$;

revoke all on function verify_owner_login(text, text) from public, anon, authenticated;
grant execute on function verify_owner_login(text, text) to service_role;

create or replace function verify_hr_manager_login(p_username text, p_password text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_match boolean;
begin
  select exists (
    select 1 from hr_manager_users
    where username = p_username
      and is_active = true
      and password_hash = crypt(p_password, password_hash)
  ) into v_match;
  return v_match;
end;
$$;

revoke all on function verify_hr_manager_login(text, text) from public, anon, authenticated;
grant execute on function verify_hr_manager_login(text, text) to service_role;

create or replace function verify_employee_login(p_username text, p_password text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_match boolean;
begin
  select exists (
    select 1 from employee_users
    where username = p_username
      and is_active = true
      and password_hash = crypt(p_password, password_hash)
  ) into v_match;
  return v_match;
end;
$$;

revoke all on function verify_employee_login(text, text) from public, anon, authenticated;
grant execute on function verify_employee_login(text, text) to service_role;

-- ---------------------------------------------------------------------
-- Privileged SQL execution. The application verifies HR/Manager/Owner session
-- before calling this trusted server-side RPC. The application validator
-- additionally prevents HR/Manager access to DataMind system tables.
-- ---------------------------------------------------------------------
create or replace function execute_privileged_sql(query text)
returns setof json
language plpgsql
security definer
set statement_timeout = '15s'
set search_path = public
as $$
begin
  if query ~* '\y(grant|revoke|merge|call|execute|vacuum|copy|listen|notify|comment)\y' then
    raise exception 'This operation is not permitted, even for privileged accounts';
  end if;

  if query ~* '\y(pg_read_file|pg_ls_dir|pg_reload_conf|lo_import|lo_export|dblink_exec|pg_terminate_backend|pg_cancel_backend)\y' then
    raise exception 'Use of a restricted database function was detected';
  end if;

  if query !~* '^\s*(select|with|insert|update|delete|create|drop|alter|truncate)(\s|$)' then
    raise exception 'Unrecognized or disallowed statement type';
  end if;

  if regexp_replace(query, ';\s*$', '') ~ ';' then
    raise exception 'Multiple statements are not allowed';
  end if;

  if query ~* '^\s*(select|with)(\s|$)' then
    return query execute format('select to_json(t) from (%s) t', query);
  else
    execute query;
    return;
  end if;
end;
$$;

revoke all on function execute_privileged_sql(text) from public, anon, authenticated;
grant execute on function execute_privileged_sql(text) to service_role;

comment on function execute_privileged_sql(text) is
  'DataMind: executes validated HR/Manager/Owner SQL from the trusted server-side application only.';
